apiVersion: apps/v1
kind: Deployment
metadata:
  name: cql-proxy-deployment
  labels:
    app: cql-proxy
spec:
  selector:
    matchLabels:
      app: cql-proxy
  template:
    metadata:
      labels:
        app: cql-proxy
    spec:
      containers:
      - name: cql-proxy
        image: kiyu/cql-proxy:1.1
        command: ["./cql-proxy"]
        #args: ["--astra-bundle=/tmp/scb.zip","--username=Client ID","--password=Client Secret"]
        args: ["--astra-bundle=/tmp/secure-connect-cvm.zip", "--astra-token='AstraCS:FldtuLSNmOcnevIIUzXwcyEb:9e45296b143b7d106b35440f08e4731b4914dcfba315a314a93131c873286757'", "--astra-databse-id='dec5b8e7-f2ed-4142-849f-e068580b07ea'", "--astra-timeout=30s", "--bind='127.0.0.1:9042'", "--data-center='us-east4'", "--track-usage", "--usage-keyspace='qt'"]
        #args: ["--astra-bundle=/tmp/secure-connect-cvm.zip", "--username='fkoFIAXGGcekwifSJwIEOHos'", "--password='C,CaIpq.wbz2lrUOz4JcfLZED7dpDD8p3gcoMNbBKCL2g0NjQNWnv4YBKfCfGH.UU9I2T,cZnTEgh8MyE,W8iyjCozdOLK9,m0X2tmELOmj3NDfXh0v5pchkuLzz1Cn4'", "--astra-timeout=30s", "--bind='127.0.0.1:9042'", "--data-center='us-east4'", "--track-usage", "--usage-keyspace='qt'"]
        volumeMounts:
        - name: my-cm-vol
          mountPath: /tmp/
        ports:
        - containerPort: 9042
          name: cql-port
          protocol: TCP
      volumes:
        - name: my-cm-vol
          configMap:
            name: cql-proxy-configmap
